---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: infrastructure
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata: 
      labels:
        app: nexus
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - image: sonatype/nexus3:3.59.0
        name: nexus
        env:
        - name: nexus_ROOT_USER
          value: "admin" 
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-vol
        ports:
        - containerPort: 8081
          name: nexus-port
        resources:
          limits:
            cpu: "4"
            memory: "4G"
          requests:
            cpu: "0.5"
            memory: "0.5Gi"
      volumes:
        - name: nexus-vol
          persistentVolumeClaim:
            claimName: nexus-pvc
---
#service
apiVersion: v1
kind: Service
metadata:
  name: service-nexus
  namespace: infrastructure
spec:
  selector:
    app: nexus
  ports:
  - name: nexus-of-service-port
    protocol: TCP
    port: 9090
    targetPort: nexus-port 
---
#ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus
  namespace: infrastructure
spec:
  ingressClassName: nginx
  rules:
  - host: "nexus.in.dxids.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-nexus
            port:
              number: 9090       
